c1:
  red: 0
  green: 255
  b: 255
  a: 255
  multiplier: 0

c2:
  r: 255
  g: 255
  b: 255
  a: 255
  multiplier: 40

c3:
  r: 255
  g: 0
  b: 255
  a: 255
  multiplier: 60

c4:
  r: 255
  g: 0
  b: 0
  a: 255
  multiplier: 120

c5:
  r: 255
  g: 255
  b: 0
  a: 255
  multiplier: 70

c6:
  r: 0
  g: 0
  b: 255
  a: 255
  multiplier: 200

c7:
  r: 0
  g: 0
  b: 0
  a: 255
  multiplier: 800
